--Insert SALARIE


--Insert ROLE

--Insert COMPETITION
INSERT INTO `COMPETITION` (`NOM`, `ANNEE`) VALUES ('Coupe D\'Afrique Des Nations', '2016-12-1');

--Insert POULE 

INSERT INTO `POULE` (`NOM`, `ID_COMPETITION`) VALUES ('A', '1');
INSERT INTO `POULE` (`NOM`, `ID_COMPETITION`) VALUES ('B', '1');
INSERT INTO `POULE` (`NOM`, `ID_COMPETITION`) VALUES ('C', '1');
INSERT INTO `POULE` (`NOM`, `ID_COMPETITION`) VALUES ('D', '1');



--Insert PAYS


--Insert MATCHE